theme: jekyll-theme-minimal
title: Sigmund Marius Nilssen
description: |
  Sigmund er techlead, løsningsarkitekt og senior systemutvikler. Han har lang erfaring med teknisk ledelse, løsningsutvikling og backend-utvikling i Kotlin, Scala og Java. Han er god til å finne enkle løsninger som gir kort time-to-market, og er opptatt av at teamet tar innsiktsbaserte avgjørelser.

  Sigmund har også lang erfaring med rekruttering, og har vært ansvarlig for fagintervjuopplegget i et selskap med mellom 100 og 200 ansatte.

  Som deltidsjobb ved siden av vanlig 100% stilling jobber Sigmund også som danseinstruktør innen Boogie Woogie, og har hatt flere verv i danseklubber opp gjennom årene.

  Hobbyer og interesser: Dans, rollespill, historie, brettspill, geopolitikk, dataspill, øl.

