theme: jekyll-theme-minimal
title: ğŸ’»ğŸ“ğŸ‘¨â€ğŸ«ğŸŒğŸ°ğŸ²ğŸ•º
description: |
  Sigmund er techlead, lÃ¸sningsarkitekt og senior systemutvikler. Han har lang erfaring med teknisk ledelse, lÃ¸sningsutvikling og backend-utvikling i Kotlin, Scala og Java. Han er god til Ã¥ finne enkle lÃ¸sninger som gir kort time-to-market, og er opptatt av at teamet tar innsiktsbaserte avgjÃ¸relser.

  Sigmund har ogsÃ¥ lang erfaring med rekruttering og personalledelse, og har vÃ¦rt ansvarlig for fagintervjuopplegget i et selskap med mellom 100 og 200 ansatte. Han har hatt direkte personalansvar for 6-10 personer siden 2011.

  Som deltidsjobb ved siden av vanlig 100% stilling jobber Sigmund ogsÃ¥ som danseinstruktÃ¸r innen Boogie Woogie, og har hatt flere verv i danseklubber opp gjennom Ã¥rene.

  Hobbyer og interesser: Dans, rollespill, historie, brettspill, geopolitikk, dataspill, Ã¸l.

